#
dev: nobody

name: DAFFtube

description: MovieStream from NoWhere

poster: /assets/images/dafftube.png

avatar: /assets/images/logo_img.png

iklanVideo: https://www.xnxx.com/embedframe/ouebubke958

disqus:

google_analytics: G-MBYBX123VX

url: https://server.daffadev.my.id

baseurl: ""

permalink: /nonton/:title

version: v1.2.0

kramdown:

  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:

    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
